<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApplicantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('applicant')->insert([
            [
                'full_name' => 'Juan Dela Cruz',
                'permanent_address' => '123 Permanent Street, Manila, Philippines',
                'current_address' => '456 Current Avenue, Quezon City, Philippines',
                'provincial_address' => '789 Provincial Road, Batangas, Philippines',
                'email' => 'juan.delacruz@example.com',
                'landline_number' => '123-4567',
                'mobile_number' => '09171234567',
                'date_of_birth' => '1990-01-01',
                'place_of_birth' => 'Manila, Philippines',
                'citizenship' => 'Filipino',
                'place_of_catholic_baptism' => 'Sto. Niño Church',
                'date_of_catholic_baptism' => '1990-02-01',
                'religious_organization_affiliated_with' => 'Knights of Columbus',
                'donors_occupation' => 'Software Engineer',
                'employers_name_or_business_name' => 'ABC Tech Solutions',
                'business_address' => 'IT Park, Cebu City, Philippines',
                'employers_email_or_business_email_address' => 'hr@abctech.com',
                'business_landline_number' => '032-5678901',
                'business_mobile_number' => '09192223333',
                'position' => 'Team Lead',
                'years_in_employment_or_business' => 5,
                'spouses_name' => 'Maria Clara Cruz',
                'spouses_date_of_birth' => '1992-03-15',
                'spouses_place_of_birth' => 'Cebu City, Philippines',
                'spouses_email_address' => 'maria.cruz@example.com',
                'spouses_landline_number' => '123-7890',
                'spouses_mobile_number' => '09175556789',
                'fathers_name' => 'Jose Dela Cruz',
                'fathers_email_address' => 'jose.cruz@example.com',
                'fathers_landline_number' => '123-5678',
                'fathers_mobile_number' => '09174445566',
                'mothers_name' => 'Juana Dela Cruz',
                'mothers_email_address' => 'juana.cruz@example.com',
                'mothers_landline_number' => '123-3456',
                'mothers_mobile_number' => '09176677889',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Maria Santos',
                'permanent_address' => '123 Main Street, Makati, Philippines',
                'current_address' => '456 Elm Street, Taguig, Philippines',
                'provincial_address' => '789 Provincial Road, Laguna, Philippines',
                'email' => 'maria.santos@example.com',
                'landline_number' => '456-7890',
                'mobile_number' => '09181234567',
                'date_of_birth' => '1995-05-10',
                'place_of_birth' => 'Makati, Philippines',
                'citizenship' => 'Filipino',
                'place_of_catholic_baptism' => 'St. Paul Parish',
                'date_of_catholic_baptism' => '1995-06-15',
                'religious_organization_affiliated_with' => 'CWL',
                'donors_occupation' => 'Teacher',
                'employers_name_or_business_name' => 'ABC Academy',
                'business_address' => 'University Belt, Manila, Philippines',
                'employers_email_or_business_email_address' => 'principal@abcacademy.com',
                'business_landline_number' => '02-8765432',
                'business_mobile_number' => '09183334444',
                'position' => 'Math Teacher',
                'years_in_employment_or_business' => 3,
                'spouses_name' => 'Carlos Santos',
                'spouses_date_of_birth' => '1994-07-20',
                'spouses_place_of_birth' => 'Cavite, Philippines',
                'spouses_email_address' => 'carlos.santos@example.com',
                'spouses_landline_number' => '456-1234',
                'spouses_mobile_number' => '09189991111',
                'fathers_name' => 'Pedro Santos',
                'fathers_email_address' => 'pedro.santos@example.com',
                'fathers_landline_number' => '456-2222',
                'fathers_mobile_number' => '09171112222',
                'mothers_name' => 'Rosa Santos',
                'mothers_email_address' => 'rosa.santos@example.com',
                'mothers_landline_number' => '456-3333',
                'mothers_mobile_number' => '09173334444',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Pedro Ramos',
                'permanent_address' => '789 Provincial Lane, Cebu, Philippines',
                'current_address' => '123 Coastal Drive, Mandaue, Philippines',
                'provincial_address' => '456 Hillside Street, Cebu, Philippines',
                'email' => 'pedro.ramos@example.com',
                'landline_number' => '789-0123',
                'mobile_number' => '09173334444',
                'date_of_birth' => '1988-03-22',
                'place_of_birth' => 'Cebu City, Philippines',
                'citizenship' => 'Filipino',
                'place_of_catholic_baptism' => 'Sacred Heart Church',
                'date_of_catholic_baptism' => '1988-04-15',
                'religious_organization_affiliated_with' => null,
                'donors_occupation' => 'Farmer',
                'employers_name_or_business_name' => null,
                'business_address' => null,
                'employers_email_or_business_email_address' => null,
                'business_landline_number' => null,
                'business_mobile_number' => null,
                'position' => null,
                'years_in_employment_or_business' => null,
                'spouses_name' => null,
                'spouses_date_of_birth' => null,
                'spouses_place_of_birth' => null,
                'spouses_email_address' => null,
                'spouses_landline_number' => null,
                'spouses_mobile_number' => null,
                'fathers_name' => 'Jose Ramos',
                'fathers_email_address' => 'jose.ramos@example.com',
                'fathers_landline_number' => null,
                'fathers_mobile_number' => '09171112222',
                'mothers_name' => 'Maria Ramos',
                'mothers_email_address' => 'maria.ramos@example.com',
                'mothers_landline_number' => null,
                'mothers_mobile_number' => '09172223333',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Carlos Diaz',
                'permanent_address' => '456 Mountain Road, Baguio, Philippines',
                'current_address' => '123 Flower Street, La Trinidad, Philippines',
                'provincial_address' => '789 Rice Field, Pangasinan, Philippines',
                'email' => 'carlos.diaz@example.com',
                'landline_number' => '123-5678',
                'mobile_number' => '09191112222',
                'date_of_birth' => '1985-12-01',
                'place_of_birth' => 'Baguio, Philippines',
                'citizenship' => 'Filipino',
                'place_of_catholic_baptism' => 'St. Joseph Parish',
                'date_of_catholic_baptism' => '1986-01-10',
                'religious_organization_affiliated_with' => 'Cursillo Movement',
                'donors_occupation' => 'Chef',
                'employers_name_or_business_name' => 'Baguio Eats',
                'business_address' => 'Session Road, Baguio, Philippines',
                'employers_email_or_business_email_address' => 'info@baguioeats.com',
                'business_landline_number' => '074-1234567',
                'business_mobile_number' => '09192223344',
                'position' => 'Head Chef',
                'years_in_employment_or_business' => 8,
                'spouses_name' => 'Anna Diaz',
                'spouses_date_of_birth' => '1986-01-15',
                'spouses_place_of_birth' => 'La Union, Philippines',
                'spouses_email_address' => 'anna.diaz@example.com',
                'spouses_landline_number' => '456-7890',
                'spouses_mobile_number' => '09178889999',
                'fathers_name' => 'Juan Diaz',
                'fathers_email_address' => 'juan.diaz@example.com',
                'fathers_landline_number' => '789-0123',
                'fathers_mobile_number' => '09179998888',
                'mothers_name' => 'Maria Diaz',
                'mothers_email_address' => 'maria.diaz@example.com',
                'mothers_landline_number' => '789-3456',
                'mothers_mobile_number' => '09172223344',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ana Garcia',
                'permanent_address' => '123 Hilltop Road, Davao, Philippines',
                'current_address' => '456 Seaside Drive, Davao, Philippines',
                'provincial_address' => '789 Farm Village, Davao del Sur, Philippines',
                'email' => 'ana.garcia@example.com',
                'landline_number' => null,
                'mobile_number' => '09192229999',
                'date_of_birth' => '1992-08-15',
                'place_of_birth' => 'Davao, Philippines',
                'citizenship' => 'Filipino',
                'place_of_catholic_baptism' => 'San Pedro Cathedral',
                'date_of_catholic_baptism' => '1992-09-10',
                'religious_organization_affiliated_with' => 'Charismatic Renewal',
                'donors_occupation' => 'Nurse',
                'employers_name_or_business_name' => 'Davao Medical Center',
                'business_address' => 'Medical Drive, Davao, Philippines',
                'employers_email_or_business_email_address' => 'admin@davaomedical.ph',
                'business_landline_number' => '082-7654321',
                'business_mobile_number' => '09193334444',
                'position' => 'Head Nurse',
                'years_in_employment_or_business' => 6,
                'spouses_name' => null,
                'spouses_date_of_birth' => null,
                'spouses_place_of_birth' => null,
                'spouses_email_address' => null,
                'spouses_landline_number' => null,
                'spouses_mobile_number' => null,
                'fathers_name' => 'Luis Garcia',
                'fathers_email_address' => 'luis.garcia@example.com',
                'fathers_landline_number' => null,
                'fathers_mobile_number' => '09174445567',
                'mothers_name' => 'Carmen Garcia',
                'mothers_email_address' => 'carmen.garcia@example.com',
                'mothers_landline_number' => null,
                'mothers_mobile_number' => '09173337777',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}